---
title: "ann_file"
author: "Gino Assenmacher, Nathan Koenig, Johanna Langemeyer, Lukas Resch, Ben Roemer"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

spotify <- read.csv("spotify.csv")
spotify_random <- read.csv("spotify_random.csv")
spotify_train <- read.csv("spotify_train.csv")
spotify_test <- read.csv("spotify_test.csv")
spotify_train_dummy <- read.csv("spotify_train_dummy.csv")
spotify_test_dummy <- read.csv("spotify_test_dummy.csv")
spotify_train_norm <- read.csv("spotify_train_norm.csv")
spotify_test_norm <- read.csv("spotify_test_norm.csv")

```

## NEURAL NETWORK MODEL

```{r}

library(caret)
library(C50)
library(irr)
library(ROCR)

train_ann <- spotify

train_ann$target <- as.factor(train_ann$target)

levels(train_ann$target) <- c("first_class", "second_class")

nnetGrid <-  expand.grid(size = seq(from = 1, to = 5, by = 1),
                        decay = seq(from = 0.1, to = 0.5, by = 0.1))

library(caret)
set.seed(123)
ctrl <- trainControl(method = "cv", number = 5, classProbs = TRUE, summaryFunction = twoClassSummary)

ann_model <- train(target ~ ., 
                            data = train_ann, 
                            metric = "ROC", 
                            tuneGrid = nnetGrid, 
                            method = "nnet",
                            trControl = ctrl, 
                            verbose = FALSE,
                            trace = FALSE)

ann_predictions <- as.data.frame(predict(ann_model, train_ann))

names(ann_predictions)[names(ann_predictions) == "predict(ann_model, train_ann)"] <- "target"

ann_predictions$target <- ifelse(ann_predictions$target == "first_class", 0, 1)

write.csv(ann_predictions, "C:/Users/gasse/Documents/School/to414/gp2/ann_predictions.csv", row.names = FALSE)

```


