---
title: "dt_file"
author: "Gino Assenmacher, Nathan Koenig, Johanna Langemeyer, Lukas Resch, Ben Roemer"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

spotify <- read.csv("spotify.csv")
spotify_random <- read.csv("spotify_random.csv")
spotify_train <- read.csv("spotify_train.csv")
spotify_test <- read.csv("spotify_test.csv")
spotify_train_dummy <- read.csv("spotify_train_dummy.csv")
spotify_test_dummy <- read.csv("spotify_test_dummy.csv")
spotify_train_norm <- read.csv("spotify_train_norm.csv")
spotify_test_norm <- read.csv("spotify_test_norm.csv")

```
```{r}
#creating test and train sets
spotify_dt <- spotify

library(C50)
library(class)
library(caret)
library(gmodels)


ctrl <- trainControl(method = "cv",
                     number = 10, repeats = 10)

grid_c50 <- expand.grid(.model = "tree",
                        .trials = c(10, 20, 30, 40),
                        .winnow = "FALSE")

set.seed(300)

dt_model <- train(as.factor(target) ~ ., 
                            data = spotify_dt, 
                            metric = "Kappa", 
                            tuneGrid = grid_c50, 
                            method = "C5.0",
                            trControl = ctrl, 
                            verbose = FALSE,
                            trace = FALSE)

dt_model

dt_predictions <- predict(dt_model, spotify_dt, type = "raw")
dt_predictions

confusionMatrix(as.factor(dt_predictions), as.factor(spotify_dt$target), positive = "1")

```
