---
title: "gp2"
author: "Gino Assenmacher, Nathan Koenig, Johanna Langemeyer, Lukas Resch, Ben Roemer"
date: "2022-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

spot10 <- read.csv("dataset-of-10s.csv")
spot00 <- read.csv("dataset-of-00s.csv")
spot90 <- read.csv("dataset-of-90s.csv")
spot80 <- read.csv("dataset-of-80s.csv")
spot70 <- read.csv("dataset-of-70s.csv")
spot60 <- read.csv("dataset-of-60s.csv")

spot10$uri <- NULL
spot00$uri <- NULL
spot90$uri <- NULL
spot80$uri <- NULL
spot70$uri <- NULL
spot60$uri <- NULL

spot10$key <- as.factor(spot10$key)
spot00$key <- as.factor(spot00$key)
spot90$key <- as.factor(spot90$key)
spot80$key <- as.factor(spot80$key)
spot70$key <- as.factor(spot70$key)
spot60$key <- as.factor(spot60$key)

spot10$mode <- as.factor(spot10$mode)
spot00$mode <- as.factor(spot00$mode)
spot90$mode <- as.factor(spot90$mode)
spot80$mode <- as.factor(spot80$mode)
spot70$mode <- as.factor(spot70$mode)
spot60$mode <- as.factor(spot60$mode)

spot10$decade <- as.factor(spot10$mode)
spot00$decade <- as.factor(spot00$mode)
spot90$decade <- as.factor(spot90$mode)
spot80$decade <- as.factor(spot80$mode)
spot70$decade <- as.factor(spot70$mode)
spot60$decade <- as.factor(spot60$mode)

spotify <- rbind(spot10, spot00, spot90, spot80, spot70, spot60)

```

## LOGISTIC REGRESSION

```{r}

model_10 <- glm(target ~ danceability + energy + loudness + mode + speechiness + acousticness +
                         instrumentalness + liveness + valence + tempo + duration_ms + time_signature + 
                         chorus_hit + sections, data = spot10, family = "binomial")
summary(model_10)

```





## KNN

```{r}

```






## Decision Tree

```{r}

```





## SVM

```{r}

```

