---
title: "knn_file"
author: "Gino Assenmacher"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(caret)
 library(data.table)
spotify <- read.csv("spotify.csv")
spotify_random <- read.csv("spotify_random.csv")
spotify_train <- read.csv("spotify_train.csv")
spotify_test <- read.csv("spotify_test.csv")
spotify_train_dummy <- read.csv("spotify_train_dummy.csv")
spotify_test_dummy <- read.csv("spotify_test_dummy.csv")
spotify_train_norm <- read.csv("spotify_train_norm.csv")
spotify_test_norm <- read.csv("spotify_test_norm.csv")

spotify_norm_total <- rbind(spotify_test_norm, spotify_train_norm)

```

## Building the Knn-Model

```{r}
#library(class)
#library(caret)

#knn_results <- knn(train = spotify_train_norm[,-27], test = #spotify_test_norm[,-27], cl = spotify_train_norm[,27], k = 17)

#confusionMatrix(knn_results, as.factor(spotify_test_norm[,27]), positive = "1")
```

# Train the model
```{r}
## Customizing the tuning process ----
# use trainControl() to alter resampling strategy
ctrl <- trainControl(method = "cv", number = 10,
                     selectionFunction = "oneSE", repeats = 10)

# use expand.grid() to create grid of tuning parameters
grid <- expand.grid(k = c(1, 5, 7, 9, 11, 13, 15, 17, 19, 21))

# look at the result of expand.grid()
grid

# customize train() with the control list and grid of parameters 
set.seed(300)
m <- train(as.factor(target) ~ ., data = spotify_norm_total, method = "knn",
           metric = "Kappa",
           trControl = ctrl,
           tuneGrid = grid)
m

```


