---
title: "lr_file"
author: "Gino Assenmacher, Nathan Koenig, Johanna Langemeyer, Lukas Resch, Ben Roemer"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

spotify <- read.csv("spotify.csv")
spotify_random <- read.csv("spotify_random.csv")
spotify_train <- read.csv("spotify_train.csv")
spotify_test <- read.csv("spotify_test.csv")
spotify_train_dummy <- read.csv("spotify_train_dummy.csv")
spotify_test_dummy <- read.csv("spotify_test_dummy.csv")
spotify_train_norm <- read.csv("spotify_train_norm.csv")
spotify_test_norm <- read.csv("spotify_test_norm.csv")

```


```{r}

fitControl <- trainControl(method = "cv", number = 10)

lmodel <- train(as.factor(target) ~ ., data = spotify_norm, method = "glm", trControl = fitControl, family = "binomial")
summary(lmodel)

lr_predictions <- predict(lmodel, spotify_norm, type = "raw")

confusionMatrix(as.factor(lr_predictions), as.factor(spotify_norm$target), positive = "1")

write.csv(lr_predictions, "C:/Users/gasse/Documents/School/to414/gp2/lr_predictions.csv", row.names = FALSE)

```

