---
title: "stacked_model"
author: "Gino Assenmacher, Nathan Koenig, Johanna Langemeyer, Lukas Resch, Ben Roemer"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Get separate data
spotify <- read.csv("spotify.csv")
lr_predictions <- read.csv("lr_predictions.csv")
ann_predictions <- read.csv("ann_predictions.csv")
knn_predictions <- read.csv("knn_predictions.csv")
svm_predictions <- read.csv("svm_predictions.csv")
dt_predictions <- read.csv("dt_predictions.csv")

# Combine the data
combined_data <- data.frame(lr_predictions, ann_predictions, knn_predictions, svm_predictions, dt_predictions, spotify$target)

# Change dataframe labels
colnames(combined_data) <- c('LR','ANN','KNN', 'SVM', 'DT', 'Actual')
combined_data
```


## Create Stacked Model

```{r}
# Get combined data
full_predictions <- combined_data

# Build the decision tree
library(caret)
set.seed(12345)

sample <- sample(c(TRUE, FALSE), nrow(full_predictions), replace=TRUE, prob=c(0.7,0.3))
train  <- combined_data[sample, ]
test   <- combined_data[!sample, ]

error_cost <- matrix(c(0, 1, 5.5, 0), nrow = 2)

library(C50)
library(class)

spotify_final_dt <- C5.0(train[-6], as.factor(train$Actual),  
                      trials = 10, costs = error_cost)

spotify_final_dt

spotify_final_predict <- predict(spotify_final_dt, test, type = "raw")

confusionMatrix(as.factor(spotify_final_predict), as.factor(stacked_data$target), positive = "1")

```



