---
title: "svm_file"
author: "Gino Assenmacher, Nathan Koenig, Johanna Langemeyer, Lukas Resch, Ben Roemer"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Deal With Data

```{r}
# Get data
spotify <- read.csv("spotify.csv")
spotify_random <- read.csv("spotify_random.csv")
spotify_train <- read.csv("spotify_train.csv")
spotify_test <- read.csv("spotify_test.csv")
spotify_train_dummy <- read.csv("spotify_train_dummy.csv")
spotify_test_dummy <- read.csv("spotify_test_dummy.csv")

# Finalize data to use
spotify_train_norm <- read.csv("spotify_train_norm.csv")
spotify_test_norm <- read.csv("spotify_test_norm.csv")
```


## Build SVM Model

```{r}
# Build a classifier with vanilladot kernel
library(kernlab)
svm_model <- ksvm(as.factor(target) ~ ., data = spotify_train_norm,
                         kernel = "vanilladot")

# Make predictions
model_predictions <- predict(svm_model, spotify_test_norm)

#library(gmodels)
#CrossTable(tele_test$yyes, model_predictions, prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE, 
#           dnn = c('actual answer', 'predicted answer'))

# Create the confusion matrix 
library(caret)
confusionMatrix(as.factor(model_predictions), as.factor(spotify_test_norm$target), positive = "1")
```

